# Generated by Django 2.2 on 2020-08-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('SGD', 'Singapore dollar'), ('HKD', 'Hong Kong dollar'), ('USD', 'United States Dollar'), ('INR', 'Indian Rupee')], help_text='choice the currenct ', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200)),
                ('total_stock_holding_units', models.IntegerField(default=0)),
                ('total_stock_holding_cost', models.FloatField(default=0)),
                ('unrealized_gain_loss', models.FloatField(default=0)),
                ('unrealized_gain_loss_percentage', models.FloatField(default=0)),
                ('realized_gain_loss', models.FloatField(default=0)),
                ('total_gain_loss', models.FloatField(default=0)),
                ('last_transacted_date', models.DateField(auto_now_add=True)),
                ('stock_name', models.OneToOneField(help_text='User of the POST', on_delete=django.db.models.deletion.CASCADE, to='mytransaction.AllStocks')),
            ],
        ),
        migrations.CreateModel(
            name='SellStockTransactiontable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sell_transacted_date', models.DateField()),
                ('currency', models.CharField(max_length=200)),
                ('stock_sell_units', models.IntegerField(help_text='number of stocks transacted')),
                ('stock_price_per_unit', models.FloatField(help_text='price per unit')),
                ('fee', models.FloatField(help_text='Fee Payed ')),
                ('stock_total_cost', models.FloatField()),
                ('stock_transaction_cost', models.FloatField()),
                ('stock_transaction_cost_per_unit', models.IntegerField()),
                ('gain_loss_from_sell', models.FloatField()),
                ('yield_of_transaction', models.FloatField()),
                ('last_transacted_date', models.DateField(auto_now_add=True)),
                ('stock_name', models.ForeignKey(help_text='User of the POST', on_delete=django.db.models.deletion.CASCADE, to='mytransaction.AllStocks')),
            ],
        ),
        migrations.CreateModel(
            name='BuyStockTransactiontable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_buy_transacted_date', models.DateField()),
                ('currency', models.CharField(max_length=200)),
                ('stock_buy_units', models.IntegerField(help_text='number of stocks transacted')),
                ('stock_price_per_unit', models.FloatField(help_text='price per unit')),
                ('fee', models.FloatField(help_text='Fee Payed ')),
                ('stock_total_cost', models.FloatField()),
                ('last_transacted_date', models.DateField(auto_now_add=True)),
                ('stock_name', models.ForeignKey(help_text='User of the POST', on_delete=django.db.models.deletion.CASCADE, to='mytransaction.AllStocks')),
            ],
        ),
    ]
