# Generated by Django 2.2 on 2020-08-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytransaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_buy_transacted_date', models.DateField()),
                ('currency', models.CharField(max_length=200)),
                ('stock_buy_units', models.IntegerField(help_text='number of stocks transacted')),
                ('stock_price_per_unit', models.FloatField(help_text='price per unit')),
                ('fee', models.FloatField(help_text='Fee Payed ')),
                ('stock_total_cost', models.FloatField(default=0)),
                ('last_transacted_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sell_transacted_date', models.DateField()),
                ('currency', models.CharField(max_length=200)),
                ('stock_sell_units', models.IntegerField(help_text='number of stocks transacted')),
                ('stock_price_per_unit', models.FloatField(help_text='price per unit')),
                ('fee', models.FloatField(help_text='Fee Payed ')),
                ('stock_total_cost', models.FloatField(default=0)),
                ('stock_transaction_cost', models.FloatField(default=0)),
                ('stock_transaction_cost_per_unit', models.IntegerField(default=0)),
                ('gain_loss_from_sell', models.FloatField(default=0)),
                ('yield_of_transaction', models.FloatField(default=0)),
                ('last_transacted_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellstocktransactiontable',
            name='stock_name',
        ),
        migrations.AlterField(
            model_name='allstocks',
            name='currency',
            field=models.CharField(choices=[('SGD', 'Singapore dollar'), ('HKD', 'Hong Kong dollar'), ('USD', 'United States Dollar'), ('INR', 'Indian Rupee')], help_text='choice the currenct ', max_length=120),
        ),
        migrations.AlterField(
            model_name='allstocks',
            name='stock_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='stock_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mytransaction.AllStocks'),
        ),
        migrations.DeleteModel(
            name='BuyStockTransactiontable',
        ),
        migrations.DeleteModel(
            name='SellStockTransactiontable',
        ),
        migrations.AddField(
            model_name='sellstock',
            name='stock_name',
            field=models.ForeignKey(help_text='User of the POST', on_delete=django.db.models.deletion.CASCADE, to='mytransaction.AllStocks'),
        ),
        migrations.AddField(
            model_name='buystock',
            name='stock_name',
            field=models.ForeignKey(help_text='User of the POST', on_delete=django.db.models.deletion.CASCADE, to='mytransaction.AllStocks'),
        ),
    ]
