# Generated by Django 2.2 on 2020-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='please select the stock', max_length=120)),
                ('date_of_transaction', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('Sell', 'Sell'), ('Buy', 'Buy')], help_text='Bought or sell', max_length=8, null=True)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('HKD', 'Hong Kong dollar')], help_text='choice the currenct ', max_length=3)),
                ('transaction_unit', models.IntegerField(help_text='number of stocks transacted')),
                ('transaction_price_per_unit', models.FloatField(help_text='price per unit')),
                ('fee', models.FloatField(help_text='Fee Payed ')),
            ],
        ),
    ]
