# Generated by Django 2.2 on 2020-08-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstock',
            name='date_of_transaction',
            field=models.DateField(),
        ),
    ]
