# Generated by Django 2.2 on 2020-08-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0002_auto_20200815_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_previous_date', models.DateField()),
                ('stock_previous_unit', models.IntegerField()),
                ('stock_cumulative_unit', models.IntegerField(help_text='number of stocks transacted')),
                ('stock_previous_cost', models.FloatField()),
                ('cost_of_transaction', models.IntegerField()),
                ('cost_of_transaction_perunit', models.IntegerField()),
                ('stock_cumulative_cost', models.IntegerField()),
                ('gain_loss_from_sale', models.IntegerField()),
                ('yield_of_transactions', models.IntegerField()),
                ('cash_flow', models.IntegerField()),
                ('stock_name', models.OneToOneField(help_text='User of the POST', null=True, on_delete=django.db.models.deletion.CASCADE, to='mytransactions.AllStock')),
            ],
        ),
    ]
