# Generated by Django 2.2 on 2020-08-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0003_mytransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytransactions',
            name='stock_transacated_value',
            field=models.IntegerField(default=0, help_text='number of stocks transacted'),
            preserve_default=False,
        ),
    ]
