# Generated by Django 2.2 on 2020-08-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0004_mytransactions_stock_transacated_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytransactions',
            old_name='stock_name',
            new_name='stock_id',
        ),
    ]
