# Generated by Django 2.2 on 2020-08-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytransactions', '0005_auto_20200816_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytransactions',
            name='stock_id',
            field=models.OneToOneField(help_text='User of the POST', on_delete=django.db.models.deletion.CASCADE, to='mytransactions.AllStock'),
        ),
    ]
