# Generated by Django 2.2 on 2020-08-12 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('Div', 'Div'), ('Sell', 'Sell'), ('Buy', 'Buy'), ('Split', 'Split'), ('CapReduct', 'CapReduct')], help_text='Choice $', max_length=10)),
                ('Stock', models.CharField(help_text='please select the stock', max_length=120)),
                ('Currency', models.CharField(choices=[('USD', 'United States Dollar'), ('HKD', 'Hong Kong dollar')], max_length=120)),
                ('TransactionUnit', models.IntegerField()),
                ('TransactionPrice', models.FloatField(max_length=100)),
                ('User', models.OneToOneField(help_text='employee raising  the request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
