# Generated by Django 2.2 on 2020-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstock',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='allstock',
            name='Currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('HKD', 'Hong Kong dollar')], max_length=3),
        ),
    ]
