# Generated by Django 2.2 on 2020-08-13 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200813_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstock',
            name='user',
            field=models.ForeignKey(help_text='employee raising  the request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
