# Generated by Django 2.2 on 2020-08-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200813_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstock',
            name='Type',
            field=models.CharField(choices=[('Div', 'Div'), ('Sell', 'Sell'), ('Buy', 'Buy'), ('Split', 'Split'), ('CapReduct', 'CapReduct')], help_text='Choice $', max_length=10),
        ),
    ]
