# Generated by Django 2.2 on 2020-08-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200813_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstock',
            name='user',
        ),
        migrations.AlterField(
            model_name='allstock',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
