# Generated by Django 2.2 on 2020-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20200814_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstock',
            name='Type',
            field=models.CharField(choices=[('Div', 'Div'), ('Sell', 'Sell'), ('Buy', 'Buy'), ('Split', 'Split'), ('CapReduct', 'CapReduct')], max_length=8),
        ),
    ]
