# Generated by Django 2.2 on 2020-08-15 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_remove_allstock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstock',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.RemoveField(
            model_name='allstock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='allstock',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='allstock',
            name='transaction_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='allstock',
            name='transaction_unit',
        ),
        migrations.RemoveField(
            model_name='allstock',
            name='type',
        ),
        migrations.AddField(
            model_name='allstock',
            name='Currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('HKD', 'Hong Kong dollar')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allstock',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allstock',
            name='TransactionPrice',
            field=models.FloatField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allstock',
            name='TransactionUnit',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allstock',
            name='Type',
            field=models.CharField(blank=True, choices=[('Div', 'Div'), ('Sell', 'Sell'), ('Buy', 'Buy'), ('Split', 'Split'), ('CapReduct', 'CapReduct')], max_length=8, null=True),
        ),
    ]
