# Generated by Django 2.2 on 2020-08-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20200815_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstock',
            name='Date',
        ),
    ]
