# Generated by Django 2.2 on 2020-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20200815_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='please select the stock', max_length=120)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Sell', 'Sell'), ('Buy', 'Buy')], help_text='Bought or sell', max_length=8, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'United States Dollar'), ('HKD', 'Hong Kong dollar')], help_text='choice the currenct ', max_length=3, null=True)),
                ('transaction_unit', models.IntegerField(blank=True, help_text='number of stocks transacted', null=True)),
                ('transaction_price_per_unit', models.FloatField(blank=True, help_text='price per unit', null=True)),
                ('fee', models.FloatField(blank=True, help_text='Fee Payed ', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AllStock',
        ),
    ]
