# Generated by Django 2.2 on 2020-08-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20200815_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_stock',
            old_name='date',
            new_name='date_of_transaction',
        ),
    ]
