# Generated by Django 2.2 on 2020-08-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20200815_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Stock',
        ),
    ]
